### ISSUE TITLE
Clicking on drawer item for active screen does not close the drawer

### ISSUE THREAD

**Issue by msevestre** [react-navigation/react-navigation-drawer#10]
Hi there,

First off, thank you for a great library. It is very easy to use and it behaves as expected on iOS and Android, which is clearly not an easy task.

I just updated my app from react-navigation v1 to v2. I managed to convert every aspect of the navigation without any problem. 
There is one noticeable difference and I am wondering it it can be changed somehow.

In v1, clicking on drawerItem for the active view was simply closing the drawer.
in v2, the drawer stays open and the user has to swipe left or click on the screen to close the drawer.

Is there a way to close the drawer when the active drawer item corresponding to the active screen is selected again by the user?

Thanks for your feedback,

Cheers,
Michael

**Comment by ghert** [comment]
@msevestre You can pass onItemPress handler to drawerItems and close the drawer as a workaround for now. I agree with you, that new behaviour is strange and I didn't saw any info about this change.

```
<DrawerItems
  {...props}
  onItemPress={() => this.props.navigation.dispatch(DrawerActions.closeDrawer())}
/>
```

**Comment by msevestre** [comment]
@ghert That does not work for me. By doing that, the drawer closes indeed but the navigation to other drawer item is broken! 

What should happen is that we call this method only for the current route or sthg like that

**Comment by ghert** [comment]
@msevestre You're right, I didn't test it properly. You can check if it's focused like this:
```
<DrawerItems
  {...this.props}
  onItemPress={({route, focused}) => {
    if (focused) {
      this.props.navigation.dispatch(DrawerActions.closeDrawer());
    } else {
      this.props.navigation.navigate(route.routeName);
    }
  }}
/>
```

**Comment by msevestre** [comment]
@ghert  Works indeed. Thanks for the input.

Note; There is a shortcut for call 1: `this.props.navigation.closeDrawer()`

@brentvatne 
This should probably be fixed in the code however so I am leaving it open. Please do not hesitate to close if this is the intended behavior

**Comment by brentvatne** [comment]
hi @msevestre - if you use the latest version of react-navigation this should be resolved. if not then let me know. i imagine you're on a slightly outdated version

**Comment by brentvatne** [comment]
see: https://github.com/react-navigation/react-navigation/blame/1951a3ac4629f9dbba444c2ced63a46ab4ee4165/CHANGELOG.md#L42

**Comment by ghert** [comment]
@brentvatne I think that issue still exists :( I tested with the 2.5.1 release.
Please take a look at https://expo.io/@react-navigation/NavigationPlayground

**Comment by msevestre** [comment]
I am actually on 2.5.3
```
 "react-navigation": "^2.5.3"
```

**Comment by msevestre** [comment]
I should add that my drawer items screen are `StackNavigator`... I am not sure if the behavior is different in that case

**Comment by gyfis** [comment]
Hi, I'm still getting this issue on `2.18.2`.
