### ISSUE TITLE
drawerLockMode not supported

### ISSUE THREAD

**Issue by tonyxiao** [react-navigation/react-navigation-drawer#33]
According to the latest 3.0 documentation, drawerLockMode is still [documented as supported](https://reactnavigation.org/docs/en/drawer-navigator.html#drawerlockmode) when in fact [it is not](https://github.com/react-navigation/react-navigation-drawer/blob/master/src/views/DrawerLayout.js#L57). We should either update the docs or update the source code to actually support it. And this should also be documented as a breaking change in the release notes (actually happened as of `react-navigation-drawer` version 0.5.0 which was part of react-navigation 2.x)

**Comment by tonyxiao** [comment]
Actually the above changes breaks animation for the stack navigator due to re-rendering. However I did find a workaround which allows me to accomplish what I wanted with the drawerMode

```
Settings: {
      screen: SettingsNavigator,
      navigationOptions: ({ navigation }: any): any => {
        if (navigation.state.index > 0) {
// drawerLockMode is a no-op, but `minSwipeDistance` = 10000 effectively disables the gesture
          return { drawerLockMode: 'locked-closed', minSwipeDistance: 10000 }
        }
        return {}
      },
    },
```

**Comment by tonyxiao** [comment]
@jhaankit yes i did. And it didn't work because of this 
![image](https://user-images.githubusercontent.com/696842/48723049-73067100-ebda-11e8-9f2a-f5a47c979cbf.png)

**Comment by jhaankit** [comment]
@tonyxiao  It should work. Try doing as same as example.

Step 1: Create a Stack navigator
```
const FeedStack = createStackNavigator({
  FeedHome: FeedScreen,
  Details: DetailsScreen,
});
```
Step 2: Create a Drawer navigator
```
const DrawerNavigator = createDrawerNavigator({
  Feed: FeedStack
});
```
Step 3: return drawerLockMode on stack navigationOptions. The drawer lock will be applicable for FeedStack stack only.
```
FeedStack.navigationOptions = () => {
   return { drawerLockMode: 'locked-closed' }
}

```

**Comment by abn-volk** [comment]
A minimal example can be found here:
https://github.com/abn-volk/drawerLockMode. In the example, various methods are used to set the `drawerLockMode` to `locked-closed`, but the drawer is not locked.

Here's the same example but with `react-navigation` v2: https://github.com/abn-volk/drawerLockMode/tree/v2. The only change is the removal of `createAppContainer`. Everything works.

I've tried to use Snack but it doesn't work, so I've published the examples here: https://exp.host/@jibi/drawerLockMode (for v3) and https://exp.host/@jibi/drawerLockMode-v2 (for v2).

**Comment by brentvatne** [comment]
thanks for the report @tonyxiao 👋 i will investigate it

**Comment by brentvatne** [comment]
this is fixed now, if you clear your yarn.lock and reinstall react-navigation you'll get react-navigation-drawer@1.0.2 with the fix

**Comment by onitzschke** [comment]
Ok, this is the way it's working for me now. 
```
  FeedStack: {
    screen: FeedHome,
    navigationOptions: ({ navigation }: { navigation: any }) => ({
      drawerLockMode: navigation.state.index > 0 ? 'locked-closed' : 'unlocked',
    })
  }
};

**Comment by lee-aaron** [comment]
I do not see a `navigation.state.index` in my navigation object. I tried what I have right now and it still doesn't lock the drawer. Is there a solution to lock a specific route? I have the latest version of react-navigation and the react-navigation-drawer. The actual source code can be found [here](https://github.com/lee-aaron/honyomi). Thanks!

| Module  | Version |
|---|---|
|npm|6.4.0|
|react-navigation|3.3.0|
|react-navigation-drawer|1.2.0|
|node|8.11.3|
|react-native|0.58.3|
|react-native-gesture-handler|1.0.15|

```
const Stack = createStackNavigator(
  {
    Main: {
      screen: ExtendStack,
      navigationOptions: {
        header: props => <CustomHeader {...props} />
      }
    },
    Test: {
      screen: Reader,
      navigationOptions: ({navigation}) => ({
        // does not work here
        // neither does 
        drawerLockMode: navigation.state.routeName == "Test" ? 'locked-closed' : 'unlocked'
      }),
    }
  }
);

class ExtendHeader extends React.Component {
  static router = Stack.router;
  render() {
    const { navigation } = this.props;
    return <Stack navigation={navigation} screenProps={navigation.state.params} />;
  }
}

const HomeScreenRouter = createDrawerNavigator(
  {
    MyLibrary: { screen: HomeScreen },
    Sources: { screen: Sources },
    Manga: { screen: ExtendHeader }
  },
  {
    contentComponent: props => <SideBar {...props} />,
  }
);
```

**Comment by BravenxX** [comment]
@lee-aaron U have to put that code ( navigationOptions: ({navigation}) => ... ) in screens inside createDrawerNavigator({...})
